# Generated by Django 3.1.2 on 2021-04-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sliderHerramienta',
            fields=[
                ('idSlider', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='herramietas')),
            ],
        ),
        migrations.CreateModel(
            name='sliderMateriales',
            fields=[
                ('idSlider', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='materiales')),
            ],
        ),
        migrations.CreateModel(
            name='sliderPintura',
            fields=[
                ('idSlider', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='pinturas')),
            ],
        ),
    ]
